name: Build pull requests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ ubuntu-20.04 ]
        compiler: [gcc]
        python-version: [3.8]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.FWDPY11_RECIPE_ACTIONS }}

      - name: Checkout
        uses: actions/checkout@v2

      # We install the R dependencies first
      # Later, Python dependencies will go into the same place.
      # Python will silently update dependencies if needed,
      # and they'll get cached, too.
      - name: Cache dependancies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.local
          key: ${{ matrix.python }}-${{ hashFiles('requirements/install.R') }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install apt dependencies
        run: |
          sudo apt-get --fix-missing -y install $(cat requirements/apt.txt)

      - name: Set GCC as compiler
        if: matrix.compiler == 'gcc'
        run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - name: Test compiler
        if: matrix.compiler == 'gcc'
        run: |
          $CXX -v
          $CC -v

      - name: Edit PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --user  "pybind11[global]"
          python -m pip install --user --upgrade -r requirements/requirements.txt

      - name: Test that fwdpy11 is discoverable
        run: |
          python -c "import fwdpy11; print(fwdpy11.__version__)"
          python -m fwdpy11 --help

      - name: Install R dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir ~/.local/Rlibs
          R --no-save < requirements/install.R

      - name: Build the book
        run: |
          R_LIBS_USER=~/.local/Rlibs make
