name: Build pull requests

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ ubuntu-20.04 ]
        compiler: [gcc]
        python-version: [3.8]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.FWDPY11_RECIPE_ACTIONS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install apt dependencies
        run: |
          sudo apt-get --fix-missing -y install $(cat requirements/apt.txt)

      - name: Set GCC as compiler
        if: matrix.compiler == 'gcc'
        run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - name: Test compiler
        if: matrix.compiler == 'gcc'
        run: |
          $CXX -v
          $CC -v

      - name: Install Python dependencies
        run: |
          python -m pip install "pybind11[global]"
          python -m pip install --upgrade -r requirements/requirements.txt

      - name: Test that fwdpy11 is discoverable
        run: |
          python -c "import fwdpy11; print(fwdpy11.__version__)"
          python -m fwdpy11 --help

      - name: Install R dependencies
        run: |
          sudo R --no-save < requirements/install.R

      - name: Build the book
        run: |
          make
